// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdXJlBo5vTbc1sVIGqnpyiKFG-cHoc1CI',
    appId: '1:733120024623:web:ee0d45d40b80ee0204f6da',
    messagingSenderId: '733120024623',
    projectId: 'poetry-editor-ai',
    authDomain: 'poetry-editor-ai.firebaseapp.com',
    storageBucket: 'poetry-editor-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjm3ec6eSTr8mqjGYH_V0s19Vw46UOciY',
    appId: '1:733120024623:android:8c977a29489d0c9604f6da',
    messagingSenderId: '733120024623',
    projectId: 'poetry-editor-ai',
    storageBucket: 'poetry-editor-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKkIBUw3UHLA8p--0AQowQWv_WY8ZAiHw',
    appId: '1:733120024623:ios:93c18fdce026e4ee04f6da',
    messagingSenderId: '733120024623',
    projectId: 'poetry-editor-ai',
    storageBucket: 'poetry-editor-ai.appspot.com',
    iosClientId: '733120024623-tfuq17k67oi3m4rtkbj4a5mbkvojvr59.apps.googleusercontent.com',
    iosBundleId: 'com.example.poetryAi',
  );
}
